# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneusage',
            name='hours_used',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
